// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

// Injectors from wire.go:

func EventProvider() (*Event, error) {
	message := NewMessage()
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event, nil
}
